# Generated by Django 3.2.15 on 2022-09-03 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('heu_username_hash', models.CharField(db_index=True, max_length=128)),
                ('score', models.CharField(db_index=True, max_length=16)),
                ('grade', models.CharField(db_index=True, max_length=32)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseinfo')),
            ],
            bases=('common.basemodel',),
        ),
    ]
