# Generated by Django 3.2.15 on 2022-09-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorerecord',
            name='grade',
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='score_raw_content_hash',
            field=models.CharField(db_index=True, default=1, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='term',
            field=models.CharField(default=1, max_length=48),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='test',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='score',
            field=models.CharField(max_length=24),
        ),
    ]
